### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eranation** [dpavkov/network-analysis-metrics#1]
Hi, 
This looks really great!
Will you please add a license? (e.g. Apache 2 / MIT / whatever you wish)
I'd like to contribute but I don't know what is your intended licensing for this.
Thanks again for sharing this, it's great! 

p.s. would you be interested in porting this from Akka to Spark / GraphX? 

Thanks again, 
Eran

**Comment by dpavkov** [comment]
Hey, thanks a lot!

License added. I'm very sorry for the slow response. You know, life and all. 

Feel free to contribute if you wish, of course. I don't have any plans for further development at this point.
